language: go

go:
  - 1.1


# Before install runs before install, we might want to use
# make install-dependencies
# however, that would probably not work properly with Travis's idea of
# the build/test matrix. (It would always install the stable version of
# go over whatever go is installed, etc.)
# before_install:
before_install:
  # It seems the Travis CI bots already have "mongodb-10gen 2.4.4"
  # available. Hopefully that one includes the SSL flags we need.
  # Otherwise the following "apt-get install" fails because of a
  # conflict on /etc/mongodb.conf
  #- sudo add-apt-repository -y ppa:juju/stable
  - sudo apt-get update
  # We should already have golang available
  - sudo apt-get install -y build-essential bzr distro-info-data git-core mercurial zip

# Default install is
# install: go get -d -v ./... && go build -v ./...
# "go get" doesn't support specifying an exact revision
install: go get -d -v ./... && go build -v ./...

script: go test -v ./...

after_success: gofmt -w -l .

