language: go

go:
  - 1.1


# Before install runs before install, we might want to use
# make install-dependencies
# however, that would probably not work properly with Travis's idea of
# the build/test matrix. (It would always install the stable version of
# go over whatever go is installed, etc.)
# before_install:
before_install:
  - sudo add-apt-repository -y ppa:juju/stable
  - sudo apt-get update
  # We should already have golang available
  # Travis CI bots have mongodb-10gen available, but it doesn't seem to have
  # the sslOnNormalPorts flag that we need to start mongodb. So we have to
  # unistall it (otherwise it conflicts) and install the actual one.
  - sudo apt-get remove -y mongodb-10gen
  - sudo apt-get install -y mongodb-server build-essential bzr distro-info-data git-core mercurial zip

# Default install is
# install: go get -d -v ./... && go build -v ./...
# "go get" doesn't support specifying an exact revision
install: go get -d -v ./... && go build -v ./... && go test -i ./...

script: go test -v ./...

after_success: gofmt -w -l .

